### ISSUE TITLE
Letting go of this repository/org?

### ISSUE THREAD

**Issue by falkTX** [wineasio/wineasio-old-docs#6]
Hi there.

I have been in talks with the original WineASIO developer @jhernberg and I am taking over the WineASIO project.
Would be nice to have the github organization as a place in github to host and report issues, and all other project related things.

I am contacting you to make you aware and ask if we can have this repo, so we can use it and be slightly more official.
Thanks!

**Comment by mcnster** [comment]
Hi Filipe,

You are welcome to it!  Let me know your details on github and I'll transfer it to you.  I no longer use any windoze software, so its not very interesting anymore.

Michael

On Friday, February 14, 2020 16:21 CET, Filipe Coelho <notifications@github.com> wrote:
 
Hi there.
I have been in talks with the original WineASIO developer @jhernberg and I am taking over the WineASIO project.
Would be nice to have the github organization has a place in github to host and report issues, and all other project related things.
I am contacting you to make you aware and ask if we can have this repo, so we can use it and be slightly more official.
Thanks!

**Comment by falkTX** [comment]
Hi!

Well, it is about the organization, so if you could add me as admin there I think I can take care of the rest.

**Comment by falkTX** [comment]
hmm any news on this? I can ping here the original develop if you wish.
@jhernberg can you leave a comment here please?

**Comment by falkTX** [comment]
@mcnster do you need assistance on github related things?

**Comment by jhernberg** [comment]
I'm all for falkTX to take over this.  Don't know where www.wineasio.org comes from, as I never created it.

**Comment by ismaelgv** [comment]
Is this still blocked? I am not sure where to report issues, here or https://github.com/falkTX/wineasio

**Comment by falkTX** [comment]
I havent heard a single thing since my last message :(
Hope everything is alright

For now use my repo to report tickets, I can move over tickets to a new repo if it comes down to it.
I suppose it is not going to be that many.

**Comment by ismaelgv** [comment]
Thanks @falkTX I will do that.

**Comment by mcnster** [comment]
The code is now uploaded and it is stable in the context of FL Studio 20 and Wine 5.x.

**Comment by falkTX** [comment]
hmmm there is an obvious miscommunication here...
please *do not host the code yourself* if you are not maintaining it.
you also added the wrong code anyway, the version I am maintaining now has additions that yours do not.
you are basically creating yet-another-repository for wineasio, exactly what we (the wineasio developers) are trying to avoid.

what we asked for is for you to willingly give up this repo and organization, so the actual wineasio developers can take it and use it as the official repositories.
so, are you interested on that or not?
I am holding on a new wineasio release (the v1.0.0) because of this.

**Comment by jhernberg** [comment]
Yes please leave this repository for the official version of wineasio maintained by falkTX!  Like that I can remove the older sourceforge code and point everyone to this repository.

If you want to maintain your own version of it, please do so as mcnster/wineasio!

**Comment by mcnster** [comment]
FalkTX,

I have added you as a project owner.  You have free reign.

I will ensure that the wineasio.org domain gets renewed at the registry.  Its the least I can do.

If your code has additional features (I haven't looked at it, but will take you at your word), its better for the users, better for you, and better for me.

Have at 'er!

- Michael -

**Comment by jhernberg** [comment]
@mcnster Thanks alot!

**Comment by falkTX** [comment]
yeah, thank you!
I have been busy with carla 2.1-rc2 release, will try to give some attention to wineasio too.
current plan is a release on the april 15th.

**Comment by falkTX** [comment]
sorry been quite a lot busy recently.
but the project was given as asked here, thank you.
