### ISSUE TITLE
Undefined reference to strrchrW

### ISSUE THREAD

**Issue by moliata** [wineasio/wineasio-old-docs#9]
Hello!

I have been trying to compile WineASIO but something doesn't seem to be working. I configured my Wine lib include path, installed libjack-dev and qjackctl but keep getting these weird undefined reference errors.

```
/usr/bin/ld: jackasio.o: in function `get_client_name_param':
/opt/wineasio/jackasio.c:1358: undefined reference to `strrchrW'
/opt/wineasio/jackasio.c:1361: undefined reference to `strrchrW'
/opt/wineasio/jackasio.c:1366: undefined reference to `tolowerW'
```

Best regards,
Ben.
P.S: I'm on wine-staging 5.7 at the moment.

**Comment by compucat** [comment]
Confirming this error; I've duplicated it on Ubuntu focal, wine-staging 5.7.

**Comment by compucat** [comment]
Ignore my previous comment: seems I had mismatched Wines on my system...traces of 5.5 here and there.
Purging all Wine-related packages, wine-staging 5.7 is being quite annoying, as is wine-devel (5.7). (I can't even get regsvr32 or other applications to run.) Of course, wine-stable is ancient and breaks my DAW (Ableton 9.7.7)

**Comment by mcnster** [comment]
Confirmed the error exists.

Renamed the functions to reflect the new WINE/Windoze symbols.  Fixed.

**Comment by moliata** [comment]
The compilation issue seems to be fixed.

Ableton 10 can't open the ASIO driver though but this seems to be a problem on my end.
